//
// Created by RGAA on 8/12/2024.
//

#include "udp_connection.h"
#include "tc_common_new/log.h"
#include <asio2/asio2.hpp>
#include <asio2/udp/udp_client.hpp>

namespace tc
{

    UdpConnection::UdpConnection(const std::string &host, int port) {
        this->host_ = host;
        this->port_ = port;
    }

    void UdpConnection::Start() {
        udp_client_ = std::make_shared<asio2::udp_client>();
        // Provide a kcp conv, If the conv is not provided, it will be generated by the server.
        //client.set_kcp_conv(12);

        udp_client_->bind_connect([&]() {
            if (asio2::get_last_error())
                LOGI("connect failure : {} {}",
                       asio2::last_error_val(), asio2::last_error_msg().c_str());
            else
                LOGI("connect success : {} {}",
                       udp_client_->local_address().c_str(), udp_client_->local_port());

            // has no error, it means connect success, we can send data at here
            if (!asio2::get_last_error()) {
                udp_client_->async_send("1<abcdefghijklmnopqrstovuxyz0123456789>");
            }

        }).bind_disconnect([]() {
            LOGI("disconnect : {} {}",
                   asio2::last_error_val(), asio2::last_error_msg().c_str());

        }).bind_recv([&](std::string_view data) {
            LOGI("recv : {}bytes", data.size());

            std::string s;
            s += '<';
            int len = 33 + std::rand() % (126 - 33);
            for (int i = 0; i < len; i++) {
                s += (char) ((std::rand() % 26) + 'a');
            }
            s += '>';

            udp_client_->async_send(std::move(s));

        }).bind_handshake([&]() {
            if (asio2::get_last_error())
                LOGI("handshake failure : {} {}",
                       asio2::last_error_val(), asio2::last_error_msg().c_str());
            else
                LOGI("handshake success : {} {}",
                       asio2::last_error_val(), asio2::last_error_msg().c_str());
        }).bind_init([&]() {
            // Specify the local port to which the socket is bind.
            //asio::ip::udp::endpoint ep(asio::ip::udp::v4(), 1234);
            //client.socket().bind(ep);
        });

        // to use kcp, the last param must be : asio2::use_kcp
        udp_client_->async_start(host_, port_, asio2::use_kcp);
    }

    void UdpConnection::Stop() {

    }

}